# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3edd3da771af02eed22ffbfdf77c04d84afc21f611a0f0418c61d9b3dffbec55693370af9fd56749303475d1e41b12121f3cad3823d051b080e2d3339ee4ce02

test:
  secret_key_base: 90173825fb3e04d794597d1c5b8e7be06d4d04c35ada9bc18cb305bca9f14f994df95c4de817422e00b075cc78435951a5ca0fbd6a9e3c04756572a2ce7015e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
